/* IMS database script */
<insert>

/* indexes */

    CREATE INDEX TRANSACTION_ID ON TRANSACTION_ (ID);
    CREATE INDEX TRANSACTION_ACCOUNT_ID ON TRANSACTION_ (ACCOUNT_ID);
    CREATE INDEX INVESTMENT_ORDER_ID ON INVESTMENT_ORDER (ID);
    CREATE INDEX ACCOUNT_ID ON ACCOUNT (ID);
    CREATE UNIQUE INDEX ACCOUNT_HID ON ACCOUNT (HARMONEY_ACCOUNT_NUMBER);
