/* IMS database script */
<insert>

/* indexes */

    CREATE INDEX TRANSACTION_ID ON TRANSACTION_ (ID);
    CREATE INDEX TRANSACTION_ACCOUNT_ID ON TRANSACTION_ (ACCOUNT_ID);
    CREATE INDEX INVESTMENT_ORDER_ID ON INVESTMENT_ORDER (ID);
    CREATE INDEX ACCOUNT_ID ON ACCOUNT (ID);
    CREATE UNIQUE INDEX ACCOUNT_HID ON ACCOUNT (HARMONEY_ACCOUNT_NUMBER);
    CREATE INDEX BILL_ID ON BILL (ID);
    CREATE INDEX BILL_LOAN_ACCOUNT_ID_DUE ON BILL (LOAN_ACCOUNT_ID,DUE_DATE);
    CREATE INDEX LOAN_ACCOUNT_ID ON LOAN_ACCOUNT (ID);
    CREATE INDEX PROTECT_REALISED_REVENUE_ORDER_ID_DUE ON PROTECT_REALISED_REVENUE (INVESTMENT_ORDER_ID,DUE_DATE);
    CREATE INDEX PROTECT_REALISED_REVENUE_LOAN_ACCOUNT_ID_DUE ON PROTECT_REALISED_REVENUE (LOAN_ACCOUNT_ID,DUE_DATE,PROTECT_REALISED_DATE);
